# Generated by Django 5.2.4 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
